name: Test Python module
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - uses: actions/checkout@v1

      - name: Test
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          test "`python main.py`" == "3"
